# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7185f12741beb1a94a48a41fa3c05a67f2174b05baa41252787cb7c4e5cd88ac53c1a36e9e4ce7e53a49569a257bf9f9617998ccaae775c5bce5fb1d80515b40

test:
  secret_key_base: d3f6fc4043702508b3d14d5a5904b968e848ea0f6404e7076a67901d742f2bbd47e19fcfbb5779bd3bc16d914ecffcc7937a5b285464b7f9da30344c62343dfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
